# Generated by Django 2.2.18 on 2021-02-15 09:46

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reset_network_people', '0003_add_section_sub_text_people_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetnetworkpeoplepage',
            name='content_long_text',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Text'),
        ),
    ]
