name-template: '$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'Type: Feature'
      - 'feature'
  - title: '⚙️ Enhancements'
    labels:
      - 'Type: Enhancement'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'Type: Bug'
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🔧 Maintenance'
    labels:
      - 'Type: Maintenance'
      - 'Type: Dependencies'
      - 'dependencies'
      - 'maintenance'
template: |
  ## Changes

  $CHANGES

  Contributors to this release: $CONTRIBUTORS
