# Generated by Django 2.2.18 on 2021-02-15 09:46

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reset_network_work', '0003_auto_20200303_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetnetworkworkpage',
            name='content_long_text',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Text'),
        ),
    ]
