# Generated by Django 2.2.18 on 2021-02-16 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_customimage_drupal_id'),
        ('reset_network_work', '0005_add_content_bottom_to_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetnetworkworkpage',
            name='content_bottom_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage', verbose_name='Image'),
        ),
    ]
