# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
executors:
  python:
    docker:
      - image: cimg/python:3.9
  node:
    docker:
      - image: cimg/node:12.22
  with-database:
    docker:
      - image: cimg/python:3.9
        environment:
          DATABASE_URL: postgresql://hypha:hypha@localhost/hypha?sslmode=disable
          DJANGO_SETTINGS_MODULE: hypha.settings.test
          SEND_MESSAGES: false
      - image: cimg/postgres:12.9
        environment:
          POSTGRES_USER: hypha
          POSTGRES_PASSWORD: hypha
          POSTGRES_DB: hypha


jobs:
  test-fe:
    executor: node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: set owner on /usr/local
          command: sudo chown -R circleci:circleci /usr/local
      - restore_cache:
          keys:
            - v3-npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v3-npm-{{ .Branch }}-
            - v3-npm-
      - run:
          name: Run functional unit test cases [REACT.JS]
          command: |
            npm install --quiet
            npm run test:ci
      - save_cache:
          paths:
            - ./node_modules
          key: v3-npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules

  build-fe:
    executor: node
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: set owner on /usr/local
          command: sudo chown -R circleci:circleci /usr/local
      - run:
          name: builds static assets
          command: |
            npm install -g gulp-cli
            gulp deploy
      - persist_to_workspace:
          root: ~/repo
          paths:
            - hypha/static_compiled

  build-be:
    executor: python
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: set owner on /usr/local
          command: sudo chown -R circleci:circleci /usr/local
      - restore_cache:
          keys:
            - v3-python-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
            - v3-python-{{ .Branch }}-
            - v3-python-
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install coverage codecov
            pip install -r requirements-dev.txt
      - save_cache:
          paths:
            - ./venv
          key: v3-python-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - venv

  test-be:
    executor: with-database
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py check
            python manage.py makemigrations --check --noinput --verbosity=1
            coverage run --source='hypha' manage.py test
            codecov

  lint:
    executor: python
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 ./hypha
            make sort


workflows:
    version: 2.1
    process:
      jobs:
        - test-fe
        - build-fe:
            requires:
            - test-fe
        - build-be
        - test-be:
            requires:
            - build-fe
            - build-be
        - lint:
            requires:
              - build-be
