# Generated by Django 2.2.18 on 2021-02-15 19:50

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reset_network_about', '0003_add_long_text_to_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetnetworkaboutpage',
            name='section_3_text',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Text'),
        ),
    ]
