# Generated by Django 2.2.18 on 2021-02-15 19:50

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reset_network_home', '0002_auto_20200303_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetnetworkhomepage',
            name='section_1_text',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Text'),
        ),
    ]
